version: '3.9'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=qa_nest
    volumes:
      - qa_nest_pg_data:/bitnami/postgresql

volumes:
  qa_nest_pg_data:
